/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace hello {
    export interface HelloRequest {
        msg?: string;
    }
    export interface HelloResponse {
        msg?: string;
    }
    export interface HelloService {
        sayHello(
            data: HelloRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<HelloResponse>;
    }
}

